language: java
jdk:
- oraclejdk8
cache:
  directories:
  - '$HOME/.m2/repository'
script:
- mvn clean package
after_success:
- mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
- mvn org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken="${COVERALLS}"
